cudami:
  typeDeclarations:

    manufacturingTypes:
      - PRINT
      - HANDMADE

    mediaTypes:
      - ARTICLE
      - BOOK
      - CONTAINED
      - IMAGES
      - ISSUE
      - NEWSPAPER
      - PART
      - SERIAL
      - UNINDEPENDENT
      - WASSERZEICHEN

    subjectTypes:
      - BY
      - GENRE
      - GEO
      - INST
      - MEETING
      - PERSON
      - SHELFGROUP
      - TIME
      - TITLE
      - TOPIC
      - UNSPECIFIED

    expressionTypes:
      - mainType: TEXT
        subType: HANDMADE
      - mainType: TEXT
        subType: PRINT
      - mainType: SCORE
        subType: HANDMADE
      - mainType: SCORE
        subType: PRINT
      - mainType: MAP
        subType: HANDMADE
      - mainType: MAP
        subType: PRINT
      - mainType: IMAGE
        subType: HANDMADE
      - mainType: IMAGE
        subType: PRINT
      - mainType: SPATIAL
        subType: HANDMADE
      - mainType: SPATIAL
        subType: PRINT

    titleTypes:
      - mainType: ABBR
        subType: MAIN
      - mainType: ALT
        subType: MAIN
      - mainType: ALT
        subType: SUB
      - mainType: ALT
        subType: PART
      - mainType: FORMER
        subType: MAIN
      - mainType: FORMER
        subType: PART
      - mainType: FORMER
        subType: SUB
      - mainType: HOST
        subType:
      - mainType: MAIN
        subType: MAIN
      - mainType: MAIN
        subType: PART
      - mainType: MAIN
        subType: SUB
      - mainType: PAR
        subType: MAIN
      - mainType: PAR
        subType: PART
      - mainType: PAR
        subType: SUB
      - mainType: TRANS
        subType: MAIN
      - mainType: TRANS
        subType: PART
      - mainType: TRANS
        subType: SUB
      - mainType: UNI
        subType: MAIN
      - mainType: UNI
        subType: PART
      - mainType: UNI
        subType: SUB
