cudami:
  defaultLocale-gui: en
  server:
    address: http://localhost:9000
  
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  server:
    port: 19898

server:
  port: 9898
  server-header: "@project.name@ v@project.version@"

# upload config: see org.springframework.boot.autoconfigure.web.MultipartProperties
spring:
  servlet:
    multipart:
      # Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes respectively.
      file-size-threshold: 1MB
      location: /tmp
      max-file-size: 5MB
      max-request-size: 25MB
      # resolve-lazily: false
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
  thymeleaf:
    cache: false
    mode: HTML
    # Order of the template resolver in the chain. (order 1 is the common classpath resolver)
    template-resolver-order: 2

---

spring:
  profiles: PROD
  security:
    user:
      name: admin
      password: secret
  thymeleaf:
    cache: true
